package agents_test

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jeremygprawira/wlog/cmd/wlog/cmd/agents"
)

// TestAgents_WritesBlockAndSkills proves one run writes the block and three skills with
// front matter.
func TestAgents_WritesBlockAndSkills(t *testing.T) {
	dir := t.TempDir()
	if code := agents.Run([]string{"--dir", dir}, io.Discard, io.Discard); code != 0 {
		t.Fatalf("run exit %d", code)
	}

	block, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("AGENTS.md: %v", err)
	}
	if !strings.Contains(string(block), "<!-- wlog:start -->") || !strings.Contains(string(block), "<!-- wlog:end -->") {
		t.Errorf("AGENTS.md has no fence:\n%s", block)
	}

	for _, name := range []string{"instrument-with-wlog.md", "audit-a-handler.md", "analyze-wlog-output.md"} {
		content, err := os.ReadFile(filepath.Join(dir, ".agents", "skills", name))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if !strings.HasPrefix(string(content), "---\nname:") {
			t.Errorf("%s has no front matter:\n%s", name, content)
		}
		if !strings.Contains(string(content), "description:") {
			t.Errorf("%s front matter has no description", name)
		}
	}
}

// TestAgents_RerunReplacesBlock proves a rerun keeps the rest of the file and replaces
// only the fenced block.
func TestAgents_RerunReplacesBlock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "AGENTS.md")
	seed := "# House rules\n\nKeep this line.\n\n<!-- wlog:start -->\nold block\n<!-- wlog:end -->\n\nAnd this line.\n"
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}

	if code := agents.Run([]string{"--dir", dir}, io.Discard, io.Discard); code != 0 {
		t.Fatalf("run exit %d", code)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	for _, kept := range []string{"# House rules", "Keep this line.", "And this line."} {
		if !strings.Contains(string(content), kept) {
			t.Errorf("rerun dropped %q:\n%s", kept, content)
		}
	}
	if strings.Contains(string(content), "old block") {
		t.Errorf("rerun kept the old block:\n%s", content)
	}
	if strings.Count(string(content), "<!-- wlog:start -->") != 1 {
		t.Errorf("rerun wrote more than one block:\n%s", content)
	}
}

// TestAgents_Golden proves the generated bytes match the pinned guidance.
func TestAgents_Golden(t *testing.T) {
	dir := t.TempDir()
	if code := agents.Run([]string{"--dir", dir}, io.Discard, io.Discard); code != 0 {
		t.Fatalf("run exit %d", code)
	}
	files := map[string]string{
		"agents.md":               filepath.Join(dir, "AGENTS.md"),
		"instrument-with-wlog.md": filepath.Join(dir, ".agents", "skills", "instrument-with-wlog.md"),
		"audit-a-handler.md":      filepath.Join(dir, ".agents", "skills", "audit-a-handler.md"),
		"analyze-wlog-output.md":  filepath.Join(dir, ".agents", "skills", "analyze-wlog-output.md"),
	}
	for name, path := range files {
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		golden := filepath.Join("..", "..", "testdata", "golden", "agents", name)
		if os.Getenv("UPDATE_GOLDEN") == "1" {
			if err := os.MkdirAll(filepath.Dir(golden), 0o755); err != nil {
				t.Fatalf("mkdir: %v", err)
			}
			if err := os.WriteFile(golden, got, 0o644); err != nil {
				t.Fatalf("write golden: %v", err)
			}
		}
		want, err := os.ReadFile(golden)
		if err != nil {
			t.Fatalf("read golden %s: %v (run UPDATE_GOLDEN=1)", golden, err)
		}
		if string(got) != string(want) {
			t.Errorf("%s differs from the golden file", name)
		}
	}
}
