// Code generated by fixturegen. DO NOT EDIT.

package main

import "net/http"

// Routes registers a handler the map must skip, because a generator wrote it.
func Routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /generated", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	return mux
}
